version: "3"
services:
  text_extraction:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/esg-x-v2/text-extraction:latest
    ports:
      - "8080:8080"
    env_file:
      - .env

  # text_translation:
  #   build:
  #     context: ./text_translate
  #     dockerfile: Dockerfile
  #   image: gcr.io/esg-x-v2/text-translation:latest
  #   ports:
  #     - "8081:8080"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ~/terraform.json:/tmp/keys/terraform.json

  # mongodb_pubsub_integration:
  #   build:
  #     context: ./mongodb_pubsub_integration
  #     dockerfile: Dockerfile
  #   image: gcr.io/esg-x-v2/mongodb-pubsub-integration:latest
  #   ports:
  #     - "8082:8080"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ~/terraform.json:/tmp/keys/terraform.json
